/*
 * IMPORTANT!
 * This file has been automatically generated,
 * in order to update it's content execute "npm run update"
 */
module.exports = {
  extends: require.resolve('./base'),
  rules: {
    'mpx/custom-event-name-casing': 'error',
    'mpx/no-arrow-functions-in-watch': 'error',
    'mpx/no-async-in-computed-properties': 'error',
    'mpx/no-custom-modifiers-on-v-model': 'error',
    'mpx/no-dupe-keys': 'error',
    // 'mpx/no-dupe-v-else-if': 'error',
    'mpx/no-duplicate-attributes': 'error',
    'mpx/no-multiple-template-root': 'error',
    'mpx/no-mutating-props': 'error',
    'mpx/no-parsing-error': 'error',
    'mpx/no-reserved-keys': 'error',
    'mpx/no-side-effects-in-computed-properties': 'error',
    'mpx/no-template-key': 'error',
    'mpx/no-textarea-mustache': 'error',
    'mpx/no-unused-components': 'error',
    'mpx/no-unused-vars': 'error',
    'mpx/no-use-v-if-with-v-for': 'error',
    'mpx/no-v-model-argument': 'error',
    'mpx/require-component-is': 'error',
    'mpx/require-prop-type-constructor': 'error',
    'mpx/require-render-return': 'error',
    'mpx/require-v-for-key': 'error',
    'mpx/require-valid-default-prop': 'error',
    'mpx/return-in-computed-property': 'error',
    'mpx/use-v-on-exact': 'error',
    'mpx/valid-template-root': 'error',
    'mpx/valid-v-bind-sync': 'error',
    'mpx/valid-v-bind': 'error',
    'mpx/valid-v-cloak': 'error',
    'mpx/valid-v-else-if': 'error',
    'mpx/valid-v-else': 'error',
    'mpx/valid-v-for': 'error',
    'mpx/valid-v-html': 'error',
    'mpx/valid-v-if': 'error',
    'mpx/valid-v-model': 'error',
    'mpx/valid-v-on': 'error',
    'mpx/valid-v-once': 'error',
    'mpx/valid-v-pre': 'error',
    'mpx/valid-v-show': 'error',
    'mpx/valid-v-slot': 'error',
    'mpx/valid-v-text': 'error'
  }
}
